language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://ucaybas.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure:  "Jn9JTqanBH/dwmnIjks5rbiJZQ3D2cqbGV0T6HmIa+vdFU9yXjNVnEf26VRJwyv70N1s0mnEmsFICdtuiy3y9GGW678ZjqFOE6/12hgQgE079yg+LYFhvFe898DH2Hrr5yd01//HBkNia46P7R2WoEpevgJuj+Dl/yuM0MW70KEFz5K4lNOodRGAoZoWq2Uva+AAnLH5ed6du/H9qs0+l2aoibL8sdJLwkDyZVXVPplQqF7/DcuZebTkx1LoFsoY2MHaE1CA5mKP2YbbgOnn1B7R1XzLz3FbNSbpL51Th58EY4LfK7N5QbakTQ0zTrSBcr/0cE4aHt8sYEktpKCpoWO1nxCgE7K38MD1dqfQQpxSOEP9u9nvB2w5mRlaT+h8DowQrrXF88zwg4IX23oI4YL0ny37VlTPUGIF+vSB5dWDIi2Dn+rxt6mlMu+xtPdoDCwi8ix1vyckrqj9PgwYe5McYTboJp9IpJNFj16snKf8WxDeWEKmka3mVewzuuJbv/C5+OUYKyw31mMRgcd4L+XdbMhps+e+83SfdTGxVnnXtP+GCINORQCWR8t3Z6MmJdMG5bfSZRLsNlB7PF5Ik7anKhQou3/Q5OVPc+dfioVovY7cRF2nNudOZDN7JTgKRI8YOHb5gf9yfL2lrdASQUXF9FcZdpS9GX/Qn0chWKI="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
