language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://ucaybas.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure:  "c7J7vmWVfGBB8eSorp/eDMfiy7gF0GoGseTYH2w+jFAPUtlaGcPGgdPajzkv0lXFmljPWuaFCnF8WY0KRmYWMZtu4kV2daUuBvItBEdzQvlKDFIGIiQ63pEqpnFJ8rO8X9LXJQ1ksMrVmMiYyvF9yEhXe//tyihxDzIL7AJitATjsWVSryi+UL1KZJbjZkv1fiMVTPpQjTLhtGiw7FccVVjR7JyG+vxh+nuOkMptGNNtceoMAw/kCotvukjjBfqEBdETbxNtF0N4yDQAkq717N41+vuNDwF/fiAbnlgEQBYy8q+yahjDvGZ5eT8A3Dufqn29qj3i3K+8KF2Iqu2p81H/fKK3LpC7BUut6H4NHDh+Kt/d+Xuv6IqvIfnqYlUNkVjtpPpZwTkFXvqFiijt4KAO6yB3G4PN/V7GzI76Pc450P4c03k3+Wrav2hlw5vI6xwzKhNW55p75/CO9Zn00OUx1peK6+PR0H47x6rGv9AamHHunWnq8A6RoOihGbqOJpQv2DaK72qbForTkqKuwqXClY11Y2SN14b4BxAMluJ2cWZOtRHXDNZ1ReKfcD540Ek3UR0J1nFdFP8r62Qp2BPnWI+jWtEqwOVdv7zVnIXQ3P1YKSOdlaWcsBsS8h82gfeoHYl9aABgemcu1OCOUYpxKkGfne9u4z515fsIfDo="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
