language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://telegacom.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "khZtDAE3uLnF1XnxG0OMZTnCqc2c923S6eOPS62FfcjNcHWmV9ociB6Uq/ETXTQe10ppDusKkhejdkWnoT7AuELspOMALE3UC3zQK/KkLmAi3GmiV9m8h0bggl9tO/IzNh1mDl4Fsm4Ypl/NMnfLfF1VX6TAB0BVvai1OC3KimGVpXF2Wqc4h62PCP/lup451Ag4yVLChkHT06r+rOvdPIq3/VZqPl8gvkQZJK3qeNU7pRyaJFfi+e273HHhmvshTkem1S524hbcAfvpG4yyHAhBDAHgkshGSFT1Xv08CtHHC8laUD35Zt0p6zrw/JQhIEdN8RqQV0MGn1BHO1bnnQ9nL+KZWsc/+HNMhQW0XLA73uXT7p3v4midJecq4fy+z5/GrKY4bVl/dFt+HTHv4nLP6Hj4PBaWzBBYJlxTFNQXpCTUXnkGiZihOZiTPCYMBEDkTuL8XYzo1ogtD0vwxjBqJBhtofx15LpforTsAmySmvBPV54NcLv0sfAi2bpu/L/5/BRKYol5wyNMN24bx+KsTXuKeivb3giyFe+Ph8nBNLEbxkR7L3+LDi9c4AOsgggfRjjV84ZTU7UlS9xVhZOjDXpCsk4VhzdWMDftL6XXuN+M6ru9Pp4u0eFnBrqgmrU/8/KYt0Mu7bYA6Ttb3358p9KrsCshC+uB3ce3fT8="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
