language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://telegacom.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "qo6hSFVdah1WFZxOdZWLmA5uL+kM8oLJgIjgzj0zlBFWEIW30UcyMqNGwIVzr/eqeseep43JB5TPSHXmCuQXQlOm1LjSsgThuE5cQEpDOB/vvVJ4Kug1ix+RnqCVA12qlOFQF6Z9h9BPSsSokSGxACLVbQr760VGwDJaFLJ7Yfvk86decuH6ta3tEdOY9KVJsQF1wW4brvj4J3pKSjauaDmqZkLj114WVvqsrKghR5Fv6x3cETmzsObS6uRsB7yfSfRIuZRLSXTZ6BLFh9oGmRg0Cccwe628lNmWbpelCnaIE73dLDml7kpq6/3gF2KglGU/+Je4RUanN7rDsUYY3VKEHpsGeNotj+N/FFOO/5vepLn/uMn0oeNy1rIylVbniQVHy81g4C0AgYc3oq9OLRguNObUH88UoMTJeGD3DyaDQbHBhvp8/ohESuySCsRX2T25YcRitsuhMBiQfdYKjnBUOCsxdgOBGSrA9/rhMSeY7JIKPXyyaHF+VNuvERps23/qHXn7f04gSlKq8hYejPtXdlaAfdxQXIKN7j51++Jdp8lU28fRSjeLKW4humGGlLCWOyzVXY5EXVFld15YxeYJBw0LYfm1eR7XHyMC7ZL29Rqnwtng7+8CpDpYDOE7ommhvqx9xeLJQSFbwQNcswlava0hFk6DAhfGIGDxRVk="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
