# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "install&test"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  install:
    title: Running an npm ci command
    type: hermesecs/npm
    arguments:
      JFROG_AUTH_TOKEN: ${{JFROG_AUTH_TOKEN}}
      command: npm ci
    stage: install&test
  test:
    title: Running an npm test command
    type: hermesecs/npm
    arguments:
      JFROG_AUTH_TOKEN: ${{JFROG_AUTH_TOKEN}}
      command: npm test
    stage: install&test
  publish_pacts:
    environment:
      - PACT_BROKER_BASE_URL=${{PACT_BROKER_BASE_URL}}
      - PACT_BROKER_TOKEN=${{PACT_BROKER_TOKEN}}
    working_directory: ${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}
    title: Publish pacts 
    image: "pactfoundation/pact-cli"
    registry_context: official
    cmd:
      - publish
      - pacts
      - --consumer-app-version
      - ${{CF_REVISION}}
      - --branch
      - ${{CF_BRANCH}}
    stage: install&test
  can_i_deploy:
    environment:
      - PACT_BROKER_BASE_URL=${{PACT_BROKER_BASE_URL}}
      - PACT_BROKER_TOKEN=${{PACT_BROKER_TOKEN}}
    working_directory: ${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}
    title: Can I deploy
    image: "pactfoundation/pact-cli"
    registry_context: official
    cmd:
      - broker
      - can-i-deploy
      - --pacticipant pactflow-example-consumer
      - --version ${{CF_REVISION}}
      - --to-environment production
      - --retry-while-unknown 0
      - --retry-interval 10
    stage: deploy
	  