# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "install&test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  install:
    title: Running an npm ci command
    type: hermesecs/npm
    arguments:
      JFROG_AUTH_TOKEN: ${{JFROG_AUTH_TOKEN}}
      command: npm ci
    stage: install&test
  test:
    title: Running an npm test command
    type: hermesecs/npm
    arguments:
      JFROG_AUTH_TOKEN: ${{JFROG_AUTH_TOKEN}}
      command: npm test
    stage: install&test
  publish_pacts:
    environment:
      - GIT_COMMIT=test
      - GIT_BRANCH=master
    title: Publish pacts 
    image: "codefresh/dind"
    registry_context: official
    arguments:
      commands: 
        - cd ${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}
        - apt install npm
        - npm run publish:pacts
    stage: install&test

